name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🏗️ CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'build'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'
      - 'deps'
    collapse-after: 5

exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'invalid'
  - 'wontfix'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'maintenance'
  default: patch

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**'
  - label: 'ci'
    files:
      - '.github/workflows/**'
      - '.github/actions/**'
  - label: 'dependencies'
    files:
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'requirements.txt'
      - 'Pipfile'
      - 'Pipfile.lock'
  - label: 'build'
    files:
      - 'Dockerfile*'
      - 'make-pkgconfig.sh'

template: |
  ## What's Changed

  $CHANGES

  ## Docker Image

  This release is available as a Docker image:
  ```
  docker pull ghcr.io/$OWNER/$REPOSITORY:$RESOLVED_VERSION
  ```

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG..$RESOLVED_VERSION
